# Generated by Django 5.1.3 on 2024-12-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pdf_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='uploaded_by',
        ),
    ]
